apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: ashapp
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: flask-sa
      containers:
      - name: flask-app
        image: ashwanth01/flask-app:0edc6cde11778d90f961f19c1e360a6f46292cd5
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: KUBECONFIG
          value: "/home/appuser/.kube/config"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: kubeconfig
          mountPath: /home/appuser/.kube
        startupProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        # --------------------------
        # Resource Requests & Limits
        # --------------------------
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: kubeconfig
        hostPath:
          path: /home/ubuntu/.kube




